### ISSUE TITLE
tweaks

### ISSUE THREAD

**Issue by Smittyvb** [Smittyvb/roadsides-www#16]
- [x] add blank column right (for future use as ad space)
- [x] archived roadsides: remove google map links - big, bold: ARCHIVED (over top of name of roadside)
- [x] 'Province' should read 'Province or territory' throughout the site, where appropriate
- [x] add date added to site on roadside page
- [x] remove 'wanted photos' and 'by type' in sidebar
- [x] center roadside name over photo, and center text under photo, and center photo!!!
- [x] move description to after google maps link
- [x] fix description and location sections on roadside pages to use html!!!
- [x] remove archived roadsides from alpha, province lists
- [x] bold name of roadside in alpha, province, archive lists
- [x] remove hyphen before google maps link
- [x] make google maps link work - go to specified coord!
- [x] remove underlining of roadside name on roadside pages
- [x] change 'See Map..." to read: "Search for this roadside attraction on our Google Maps page"
- [x] reset dropdown menus after navigating away from list pages
- [x] fix archive page title
- [x] remove pinterest from social media box; replace with google+
- [x] add period at end of: "Search for this roadside attraction on our Google Maps page"
- [x] move credit to below description

_edit: added new tweaks from @dr-mvb._
_edit 2: added more tweaks from @dr-mvb._

**Comment by dr-mvb** [comment]
updated tweaks:
- [ ] add period at end of: "Search for this roadside attraction on our Google Maps page"
- [ ] move credit to below description

**Comment by dr-mvb** [comment]
- [ ] 'Province' should read 'Province or territory' throughout the site, where appropriate

**Comment by Smittyvb** [comment]
In order to add "or territory" to the bar on the left side, we would have to increase its width. Should we do that?

**Comment by Smittyvb** [comment]
Also, what should the standard picture width be?

**Comment by Smittyvb** [comment]
Maybe we should wait until we actually have ads, before we add the blank right column.

**Comment by dr-mvb** [comment]
Response to above comments:
- can't we have a line break after 'province' so 'or territory' is on the next and does not increase the width?
- standard picture width: let's skip this for now - most pic's seem fine as-is
- blank right column: even without ads, I like the idea of a right column - it makes the page look better over-all

Other notes:
- for archive pages, make the text at the top in bold, in red, and read: "ARCHIVED: This roadside attraction no longer exists. Below is a record of what it used to look like." (and it should be centered)
- and on archived pages, remove the "Search for this roadside attraction on our Google Maps page."

**Comment by Smittyvb** [comment]
Splitting the dropdown menu over multiple lines isn't possible.
