### ISSUE TITLE
new tweaks

### ISSUE THREAD

**Issue by Smittyvb** [Smittyvb/roadsides-www#20]
- [x] add links to text of home page
- [x] founder page: change "this blog" to "our blog" and make that a link
- [x] on side bar: remove "..." after "territory..."
- [x] on lists (province/alpha/archive), make photo a clickable link
- [x] on archived roadsides: add "ARCHIVED: " to text at top, and make all of that text red
- [x] media page: add to link on nav bar
- [x] media page: add heading to page: "Media"
- [x] what's new page: limit to last 20 roadsides; add "Dated added to site:" in description
- [x] remove period at end of 'date added to site'
- [x] make all google maps links always open up in a new tab
- [x] change 'google maps' on roadsides to read: "GPS: [coords here]" and make coords a clickable link (and open in new tab)
- [x] google map links on pages without specific coords does not open up in new tab - in fact, still need to make all links on roadside page open up in new tabs
- [x] founder page: make "our blog" a link
- [x] on side bar: move 'what's new' to the top of the list 
- [x] add terms of use
- [x] on home page: change "--" into an em dash; also make "planes on sticks" a link
- [x] on roadside pages: make location bold; make credit line italics
- [x] redirect trans canada highway + by type to tags page, which says coming soon
- [x] make right column a tiny bit bigger
- [x] on mobile, static pages have different font sizes (contact vs. send pics most noticeable) - I don't notice it on my laptop, though
- [x] make links in descriptions and credit open as new tabs (low priority)

**Comment by Smittyvb** [comment]
also: make links in descriptions and credit open as new tabs (low priority)

**Comment by Smittyvb** [comment]
on roadside pages: make location bold; make credit line italics

**Comment by dr-mvb** [comment]
- [ ] on mobile, static pages have different font sizes (contact vs. send pics most noticeable) - I don't notice it on my laptop, though
- [ ] google map links on pages without specific coords does not open up in new tab - in fact, still need to make all links on roadside page open up in new tabs
- [ ] founder page: make "our blog" a link
- [ ] on side bar: move 'what's new' to the top of the list

**Comment by dr-mvb** [comment]
And then we go live!!!!
