### ISSUE TITLE
google searches

### ISSUE THREAD

**Issue by dr-mvb** [Smittyvb/roadsides-www#33]
- fix title of individual roadsides: include name of roadside
- description for static pages: For almost 20 years, this site has been dedicated to cataloguing Canada's varied roadside attractions.
- probably help with google indexing if we stopped the 404 re-directs

**Comment by Smittyvb** [comment]
Here's what someone would see in search results (for the main page):
![](https://s24.postimg.org/fuhie4xhh/lcrasample.png)
